# Generated by Django 3.0.5 on 2020-04-11 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No Name', max_length=70)),
                ('number', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=1)),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('commercialName', models.CharField(default='', max_length=70)),
                ('acronimo', models.CharField(default='', max_length=15)),
                ('rnc', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('email', models.CharField(max_length=70, null=True)),
                ('city', models.CharField(default='', max_length=70)),
                ('direction', models.CharField(max_length=70, null=True)),
                ('director', models.CharField(default='', max_length=70)),
                ('status', models.BooleanField(default=1)),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Locks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No Name', max_length=70)),
                ('idstring', models.CharField(default='', max_length=9)),
                ('controller', models.CharField(default='', max_length=70)),
                ('status', models.BooleanField(default=1)),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Carrier', verbose_name='Carrier')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Subject', verbose_name='Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No Name', max_length=70)),
                ('number', models.IntegerField(default=1)),
                ('floor', models.IntegerField(default=1)),
                ('lab', models.BooleanField(default=0)),
                ('capacity', models.IntegerField(default=30)),
                ('available', models.BooleanField(default=1)),
                ('status', models.BooleanField(default=1)),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Building', verbose_name='Building')),
                ('lock', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='control.Locks', verbose_name='Locks')),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=1)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Rooms', verbose_name='Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carrier',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Institutions', verbose_name='Institutions'),
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('city', models.CharField(default='', max_length=70)),
                ('direction', models.CharField(max_length=70, null=True)),
                ('phone', models.CharField(default='', max_length=15)),
                ('email', models.CharField(max_length=70, null=True)),
                ('manager', models.CharField(max_length=70)),
                ('status', models.BooleanField(default=1)),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('Institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Institutions', verbose_name='Institutions')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='Campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Campus', verbose_name='Campus'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ES', 'Estudiante'), ('PR', 'Profesor'), ('ST', 'Staf')], default='ES', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=1)),
                ('weekday', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')])),
                ('fromHour', models.TimeField()),
                ('toHour', models.TimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Subject', verbose_name='Subject')),
            ],
            options={
                'ordering': ('weekday', 'fromHour'),
                'unique_together': {('weekday', 'fromHour', 'toHour')},
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=1)),
                ('weekday', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')])),
                ('fromHour', models.TimeField()),
                ('toHour', models.TimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Rooms', verbose_name='Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('weekday', 'fromHour'),
                'unique_together': {('weekday', 'fromHour', 'toHour')},
            },
        ),
    ]
