# Generated by Django 3.0.5 on 2020-04-06 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=70, verbose_name='')),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Locks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=1)),
                ('idbuilding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Building', verbose_name='Building')),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(max_length=70, verbose_name='')),
                ('status', models.BooleanField(default=1)),
                ('idInstitution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Institutions', verbose_name='Institutions')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='idCampus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Campus', verbose_name='Campus'),
        ),
    ]
