# Generated by Django 3.0.5 on 2020-04-06 17:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='idCampus',
            new_name='Campus',
        ),
        migrations.RenameField(
            model_name='campus',
            old_name='idInstitution',
            new_name='Institution',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='idbuilding',
            new_name='building',
        ),
        migrations.AddField(
            model_name='building',
            name='createAt',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='building',
            name='name',
            field=models.CharField(default='No Name', max_length=70),
        ),
        migrations.AddField(
            model_name='building',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='building',
            name='updatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='building',
            name='updatedBy',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='campus',
            name='city',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='campus',
            name='createAt',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='campus',
            name='email',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='name',
            field=models.CharField(default='No Name', max_length=70),
        ),
        migrations.AddField(
            model_name='campus',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='campus',
            name='updatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='campus',
            name='updatedBy',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='institutions',
            name='commercialName',
            field=models.CharField(default='No Name', max_length=70),
        ),
        migrations.AddField(
            model_name='institutions',
            name='createAt',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='institutions',
            name='email',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='institutions',
            name='name',
            field=models.CharField(default='No Name', max_length=70),
        ),
        migrations.AddField(
            model_name='institutions',
            name='phone',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='institutions',
            name='rnc',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='institutions',
            name='updatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='institutions',
            name='updatedBy',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='locks',
            name='createAt',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='locks',
            name='name',
            field=models.CharField(default='No Name', max_length=70),
        ),
        migrations.AddField(
            model_name='locks',
            name='string',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='locks',
            name='updatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='locks',
            name='updatedBy',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='capacity',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='rooms',
            name='createAt',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='lab',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='lock',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='control.Locks', verbose_name='Locks'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='name',
            field=models.CharField(default='No Name', max_length=70),
        ),
        migrations.AddField(
            model_name='rooms',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rooms',
            name='updatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='updatedBy',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='campus',
            name='manager',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='director',
            field=models.CharField(default='', max_length=70),
        ),
    ]
