# Generated by Django 3.0.5 on 2020-04-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20200406_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutions',
            name='acronimo',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='commercialName',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='name',
            field=models.CharField(default='', max_length=70),
        ),
    ]
