# Generated by Django 3.0.5 on 2020-04-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20200406_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='direction',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='institutions',
            name='city',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='institutions',
            name='direction',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
