# Generated by Django 3.0.5 on 2020-04-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20200411_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='quater',
            field=models.IntegerField(default=0),
        ),
    ]
