# Generated by Django 3.0.5 on 2020-04-11 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0004_subject_quater'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.CreateModel(
            name='SubjectTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Subject', verbose_name='Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
