# Generated by Django 3.0.5 on 2020-04-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20200406_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='floor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(default='', max_length=70),
        ),
    ]
