# Generated by Django 3.0.5 on 2020-04-11 17:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0005_auto_20200411_1318'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('user', 'weekday', 'fromHour', 'toHour')},
        ),
        migrations.DeleteModel(
            name='SubjectTeacher',
        ),
    ]
