# Generated by Django 3.0.5 on 2020-04-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_auto_20200406_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='locks',
            name='controller',
            field=models.CharField(default='', max_length=70),
        ),
    ]
