# Generated by Django 3.0.5 on 2020-04-14 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_auto_20200411_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='entrada',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
