# Generated by Django 3.0.5 on 2020-04-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_auto_20200414_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='accion',
            field=models.CharField(choices=[('0', 'Entrar'), ('1', 'Cerrar'), ('2', 'Ciclo')], default='0', max_length=2),
        ),
    ]
